<a href="https://colab.research.google.com/github/2303a51853/2303a51853/blob/main/AIML_Ass_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(1.1)
list=np.array([[1],[2],[3],[4],[5]])
print(list)


1.1
[[1]
 [2]
 [3]
 [4]
 [5]]


In [2]:
import numpy as np
print(1.2)
array=np.array([1,2,3,4,5])
print(array)



1.2
[1 2 3 4 5]


In [3]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(type(arr))



<class 'numpy.ndarray'>


In [4]:
#performing mathematical operations
#1.multipilcation
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
mul=np.multiply(a,b)
print(mul)


[ 4 10 18]


In [5]:
#2.division
div=np.divide(a,b)
print(div)


[0.25 0.4  0.5 ]


In [6]:
#3,poweroff
power=np.power(a,b)
print(power)


[  1  32 729]


In [7]:
#Addition of two array
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])
r=array1+array2
print(r)


[5 7 9]


In [8]:
#implement np.sin(), log(), np.exp(), log2()
import numpy as np
a = np.array([1,2,3])
sin = np.sin(a)
print(sin)
log = np.log(a)
print(log)
exp = np.exp(a)
print(exp)
log2 = np.log2(a)
print(log2)

[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.        1.        1.5849625]
